spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/User/Desktop/UNIVERSIDAD/PDS/config-data
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9000